### ISSUE TITLE
Error after SWARP execution

### ISSUE THREAD

**Issue by johnedmartz** [maxmahlke/ssos#1]
Hi,

While using the default settings of the pipeline I have found a problem that wasn't happening before. I'm having this issue since the last time I updated ubuntu.

In a virtual machine from other pc I have installed ubuntu from scratch with only what's needed to run this pipeline, but I get exactly the same error.

I can "bypass" this problem if I add the following text to hdulist.py, from the astropy package, in the line 967.

> self._file.close()

This file is located in ... /lib/python3.7/site-packages/astropy/io/fits/hdu. I know that I shouldn't touch this files but, for now with that change, the pipeline actually finishes without errors.

Here I attach a copy of the main error.

> Extracting cutouts with SWARP../home/john/anaconda3/lib/python3.7/site-packages/tqdm/std.py:666: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
>   from pandas import Panel
> Creating cutouts:   0%| | 2/666 [00:00<02:40,  4.12cutouts/
> Exception occurred during analysis: 
> Traceback (most recent call last):
>   File "/home/john/anaconda3/bin/ssos", line 8, in <module>
>     sys.exit(main())
>   File "/home/john/anaconda3/lib/python3.7/site-packages/ssos/__main__.py", line 105, in main
>     pipeline.execute_analysis(step)
>   File "/home/john/anaconda3/lib/python3.7/site-packages/ssos/core.py", line 815, in execute_analysis
>     self.args)
>   File "/home/john/anaconda3/lib/python3.7/site-packages/ssos/opt.py", line 205, in extract_cutouts
>     sources.progress_apply(lambda row: _call_swarp(row, settings, log, paths, args), axis=1)
>   File "/home/john/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 765, in inner
>     return getattr(df, df_function)(wrapper, **kwargs)
>   File "/home/john/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 6878, in apply
>     return op.get_result()
>   File "/home/john/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py", line 186, in get_result
>     return self.apply_standard()
>   File "/home/john/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py", line 296, in apply_standard
>     values, self.f, axis=self.axis, dummy=dummy, labels=labels
>   File "pandas/_libs/reduction.pyx", line 620, in pandas._libs.reduction.compute_reduction
>   File "pandas/_libs/reduction.pyx", line 128, in pandas._libs.reduction.Reducer.get_result
>   File "/home/john/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 760, in wrapper
>     return func(*args, **kwargs)
>   File "/home/john/anaconda3/lib/python3.7/site-packages/ssos/opt.py", line 205, in <lambda>
>     sources.progress_apply(lambda row: _call_swarp(row, settings, log, paths, args), axis=1)
>   File "/home/john/anaconda3/lib/python3.7/site-packages/ssos/opt.py", line 182, in _call_swarp
>     utils.create_clean_image(cutout_filename, cutout_filename, update=True)
>   File "/home/john/anaconda3/lib/python3.7/site-packages/ssos/utils.py", line 332, in create_clean_image
>     exp.flush()
>   File "/home/john/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 389, in __exit__
>     self.close(output_verify=output_verify)
>   File "/home/john/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 971, in close
>     self.flush(output_verify=output_verify, verbose=verbose)
>   File "/home/john/anaconda3/lib/python3.7/site-packages/astropy/io/fits/util.py", line 241, in wrapped
>     func(*args, **kwargs)
>   File "/home/john/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 829, in flush
>     self.verify(option=output_verify)
>   File "/home/john/anaconda3/lib/python3.7/site-packages/astropy/io/fits/verify.py", line 66, in verify
>     opt = option.lower()
> AttributeError: 'bool' object has no attribute 'lower'

**Comment by johnedmartz** [comment]
It seems like the problem was in the astropy package. Something similar has been added to the file I was editing before.
With this new update, the problem is gone.

**Comment by maxmahlke** [comment]
Thanks for following up on this John! Seems to have been an issue with astropy indeed, good that it's resolved now.

Editing files in your python library can give you problems, but I also temporarily change lines for bug hunting. If you need more permanent changes, you can just create a new conda environment specifically for your problem.
